server:
    port: 9090
spring:
    session:
        store-type: none
    datasource:
        driverClassName: org.postgresql.Driver
        password: ENC(CzTn7iBUz3XtxUUhl1XfgvsppOzn9TK2)
        url: jdbc:postgresql://localhost:5432/postgres
        username: insurance
    jpa:
        database-platform: com.gar.system.config.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.gar.system.config.NoDefaultJCacheRegionFactory