server:
    port: 9090
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ENC()
        url: jdbc:postgresql://localhost:5432/postgres
        username: insurance