server:
    port: 9090
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ENC(CzTn7iBUz3XtxUUhl1XfgvsppOzn9TK2)
        url: jdbc:postgresql://localhost:5432/postgres
        username: insurance